// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SkyMoney_Admin_System.Models;

#nullable disable

namespace SkyMoney_Admin_System.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251211004608_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("SkyMoney_Admin_System.Models.BudgetPlan", b =>
                {
                    b.Property<int>("BudgetPlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("FundedExpenses")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalBudget")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserAccountId")
                        .HasColumnType("INTEGER");

                    b.HasKey("BudgetPlanId");

                    b.HasIndex("UserAccountId");

                    b.ToTable("BudgetPlans");
                });

            modelBuilder.Entity("SkyMoney_Admin_System.Models.FixedExpense", b =>
                {
                    b.Property<int>("FixedExpenseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<int>("BudgetPlanId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FundedAmount")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFinanced")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("FixedExpenseId");

                    b.HasIndex("BudgetPlanId");

                    b.ToTable("FixedExpenses");
                });

            modelBuilder.Entity("SkyMoney_Admin_System.Models.IncomeRecord", b =>
                {
                    b.Property<int>("IncomeRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateReceived")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserAccountId")
                        .HasColumnType("INTEGER");

                    b.HasKey("IncomeRecordId");

                    b.HasIndex("UserAccountId");

                    b.ToTable("IncomeRecords");
                });

            modelBuilder.Entity("SkyMoney_Admin_System.Models.TransactionRecord", b =>
                {
                    b.Property<int>("TransactionRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserAccountId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TransactionRecordId");

                    b.HasIndex("UserAccountId");

                    b.ToTable("TransactionRecords");
                });

            modelBuilder.Entity("SkyMoney_Admin_System.Models.UserAccount", b =>
                {
                    b.Property<int>("UserAccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("IncomeType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NextScheduledPayDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PayFrequencyDays")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserAccountId");

                    b.ToTable("UserAccounts");
                });

            modelBuilder.Entity("SkyMoney_Admin_System.Models.VariableExpense", b =>
                {
                    b.Property<int>("VariableExpenseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BudgetPlanId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CategoryBalance")
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PercentOfAvailableBudget")
                        .HasColumnType("TEXT");

                    b.HasKey("VariableExpenseId");

                    b.HasIndex("BudgetPlanId");

                    b.ToTable("VariableExpenses");
                });

            modelBuilder.Entity("SkyMoney_Admin_System.Models.BudgetPlan", b =>
                {
                    b.HasOne("SkyMoney_Admin_System.Models.UserAccount", "UserAccount")
                        .WithMany("BudgetPlans")
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("SkyMoney_Admin_System.Models.FixedExpense", b =>
                {
                    b.HasOne("SkyMoney_Admin_System.Models.BudgetPlan", "BudgetPlan")
                        .WithMany("FixedExpenses")
                        .HasForeignKey("BudgetPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BudgetPlan");
                });

            modelBuilder.Entity("SkyMoney_Admin_System.Models.IncomeRecord", b =>
                {
                    b.HasOne("SkyMoney_Admin_System.Models.UserAccount", "UserAccount")
                        .WithMany("IncomeRecords")
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("SkyMoney_Admin_System.Models.TransactionRecord", b =>
                {
                    b.HasOne("SkyMoney_Admin_System.Models.UserAccount", "UserAccount")
                        .WithMany("TransactionRecords")
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("SkyMoney_Admin_System.Models.VariableExpense", b =>
                {
                    b.HasOne("SkyMoney_Admin_System.Models.BudgetPlan", "BudgetPlan")
                        .WithMany("VariableExpenses")
                        .HasForeignKey("BudgetPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BudgetPlan");
                });

            modelBuilder.Entity("SkyMoney_Admin_System.Models.BudgetPlan", b =>
                {
                    b.Navigation("FixedExpenses");

                    b.Navigation("VariableExpenses");
                });

            modelBuilder.Entity("SkyMoney_Admin_System.Models.UserAccount", b =>
                {
                    b.Navigation("BudgetPlans");

                    b.Navigation("IncomeRecords");

                    b.Navigation("TransactionRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
